export {
  AvailabilitySchema,
  BrandEvidenceSchema,
  CampaignBlockSchema,
  CampaignGoalSchema,
  CampaignSchema,
  CtaSchema,
  EvidenceRefSchema,
  GenerateCampaignInputSchema,
  GenerationContextSchema,
  HttpUrlSchema,
  ImageSchema,
  MoneySchema,
  OfferInputSchema,
  ProductEvidenceSchema,
  ProductIdSchema,
  SCHEMA_VERSION,
} from "./core/schemas/index.js";

export type {
  Availability,
  BrandEvidence,
  Campaign,
  CampaignBlock,
  CampaignGoal,
  Cta,
  EvidenceRef,
  GenerateCampaignInput,
  GenerationContext,
  Image,
  Money,
  OfferInput,
  ProductEvidence,
  ProductId,
} from "./core/schemas/index.js";
